# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 80, 761, 241))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionabout_file = QtWidgets.QAction(MainWindow)
        self.actionabout_file.setObjectName("actionabout_file")
        self.actionrun_script = QtWidgets.QAction(MainWindow)
        self.actionrun_script.setObjectName("actionrun_script")
        self.actiondebug = QtWidgets.QAction(MainWindow)
        self.actiondebug.setObjectName("actiondebug")
        self.actionabout_Python_Editor = QtWidgets.QAction(MainWindow)
        self.actionabout_Python_Editor.setObjectName("actionabout_Python_Editor")
        self.actionabout_os = QtWidgets.QAction(MainWindow)
        self.actionabout_os.setObjectName("actionabout_os")
        self.actionreadonly = QtWidgets.QAction(MainWindow)
        self.actionreadonly.setObjectName("actionreadonly")
        self.menu.addAction(self.actionnew)
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addSeparator()
        self.menu.addAction(self.actionabout_file)
        self.menu_2.addAction(self.actionreadonly)
        self.menu_3.addAction(self.actionrun_script)
        self.menu_3.addAction(self.actiondebug)
        self.menu_4.addAction(self.actionabout_Python_Editor)
        self.menu_4.addAction(self.actionabout_os)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python编辑器-未命名"))
        self.label.setText(_translate("MainWindow", "向下滑动文本编辑框来查看"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "预览"))
        self.menu_3.setTitle(_translate("MainWindow", "运行"))
        self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionabout_file.setText(_translate("MainWindow", "about file"))
        self.actionrun_script.setText(_translate("MainWindow", "run script"))
        self.actiondebug.setText(_translate("MainWindow", "debug"))
        self.actionabout_Python_Editor.setText(_translate("MainWindow", "about Python Editor"))
        self.actionabout_os.setText(_translate("MainWindow", "about os"))
        self.actionreadonly.setText(_translate("MainWindow", "readonly"))
if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow
    app = QApplication(sys.argv)
    mw = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mw)
    mw.show()
    sys.exit(app.exec_())